version: '3.1'
services :
  postgres:
    image: postgres:10-alpine
    container_name: shop_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shop_3

  admin:
    image: adminer
    restart: always
    depends_on: 
      - postgres
    ports:
      - 8080:8080
